# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false

  # config.vm.network "public_network"
  config.vm.network "private_network", ip: "192.168.33.12"
  config.vm.synced_folder "./data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "chef_client"
    vb.memory = "1024"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
     yum update
     yum install -y vim tree
  SHELL
end
