# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder "../data/workstation", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "chef_workstation"
  #   # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
     yum update && yum install -y vim wget git zip unzip tree
     wget https://raw.githubusercontent.com/amix/vimrc/master/vimrcs/basic.vim
     cp basic.vim /home/vagrant/.vimrc

     # download chef dk
     yum install -y https://packages.chef.io/files/stable/chefdk/2.1.11/el/7/chefdk-2.1.11-1.el7.x86_64.rpm

     # use the ruby that came with chef
     echo 'eval "$(chef shell-init bash)"' >> ~/.bash_profile

     # reload the environment for it to take control
     source .bash_profile

     export VAGRANT_DATA=/vagrant_data
     export CHEF_REPO=/home/vagrant/chef-repo

  SHELL
end
